UPDATE `site_pages_pages` SET `id` = 'edit_page_templates' WHERE `uri` = '/edit_page_templates/' AND `application_id` = 'AdminPanel';
UPDATE `site_pages_pages` SET `id` = 'edit_templates' WHERE `uri` = '/edit_templates/' AND `application_id` = 'AdminPanel';
UPDATE `site_pages_pages` SET `id` = 'edit_themes' WHERE `uri` = '/edit_themes/' AND `application_id` = 'AdminPanel';
UPDATE `site_pages_pages` SET `id` = 'edit_mobile_templates' WHERE `uri` = '/edit_mobile_templates/' AND `application_id` = 'AdminPanel';
UPDATE `site_pages_pages` SET `id` = 'edit_mobile_page_templates' WHERE `uri` = '/edit_mobile_page_templates/' AND `application_id` = 'AdminPanel';
UPDATE `site_pages_pages` SET `id` = 'edit_mobile_themes' WHERE `uri` = '/edit_mobile_themes/' AND `application_id` = 'AdminPanel';
UPDATE `site_pages_pages` SET `id` = 'edit_subdomain_templates' WHERE `uri` = '/edit_subdomain_templates/' AND `application_id` = 'AdminPanel';
UPDATE `site_pages_pages` SET `id` = 'edit_subdomain_page_templates' WHERE `uri` = '/edit_subdomain_page_templates/' AND `application_id` = 'AdminPanel';
UPDATE `site_pages_pages` SET `id` = 'edit_subdomain_themes' WHERE `uri` = '/edit_subdomain_themes/' AND `application_id` = 'AdminPanel';
